/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AclConfig: typeof import('./../components/config/AclConfig.vue')['default']
    ClassicSidebar: typeof import('./../components/home/sidebar/ClassicSidebar.vue')['default']
    ConfigModal: typeof import('./../components/config/ConfigModal.vue')['default']
    ConsoleSidebar: typeof import('./../components/home/sidebar/ConsoleSidebar.vue')['default']
    CorsConfig: typeof import('./../components/config/CorsConfig.vue')['default']
    DynamicConfigForm: typeof import('./../components/config/DynamicConfigForm.vue')['default']
    HistoryGrid: typeof import('./../components/history/HistoryGrid.vue')['default']
    HistoryHeader: typeof import('./../components/history/HistoryHeader.vue')['default']
    HistoryToolbar: typeof import('./../components/history/HistoryToolbar.vue')['default']
    ImportConfigModal: typeof import('./../components/home/sidebar/ImportConfigModal.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NodeList: typeof import('./../components/home/node/NodeList.vue')['default']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./../components/settings/SettingsModal.vue')['default']
    SidebarSettings: typeof import('./../components/settings/SidebarSettings.vue')['default']
    UploadQueue: typeof import('./../components/home/queue/UploadQueue.vue')['default']
    UploadZone: typeof import('./../components/home/upload/UploadZone.vue')['default']
  }
}
